### ISSUE TITLE
输出错误

### ISSUE THREAD

**Issue by bifu123** [leeyoshinari/OneDrive#10]
(OneDrive) root@debian:~/OneDrive# sh ./startup.sh
start server success ~
(OneDrive) root@debian:~/OneDrive# lsof -i :15200

COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
gunicorn 3879 root    5u  IPv4  47221      0t0  TCP localhost:15200 (LISTEN)
gunicorn 3880 root    5u  IPv4  47221      0t0  TCP localhost:15200 (LISTEN)
(OneDrive) root@debian:~/OneDrive#

![1](https://github.com/leeyoshinari/OneDrive/assets/18096170/66090ea2-07e1-465a-882f-8dcbd80c73b7)
![2](https://github.com/leeyoshinari/OneDrive/assets/18096170/5c99c860-6720-4628-9b04-5e3876570e16)
![3](https://github.com/leeyoshinari/OneDrive/assets/18096170/3ae8198d-6969-4eaf-bbf7-3ca6d98db8bf)

**Comment by leeyoshinari** [comment]
咦，你不懂 nginx 部署吗？ 特别要注意 alias 后面的目录的最后一个 '/' 要有
