### ISSUE TITLE
有两个错误

### ISSUE THREAD

**Issue by bifu123** [leeyoshinari/OneDrive#11]
- 一、git clone不下来

(OneDrive) test@ubuntu64:~/OneDrive$ git clone https://github.com/leeyoshinari/OneDrive.git
正克隆到 'OneDrive'...
remote: Enumerating objects: 1715, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (38/38), done.
error: RPC 失败。curl 56 GnuTLS recv error (-54): Error in the pull function.
error: 预期仍然需要 5526 个字节的正文
fetch-pack: unexpected disconnect while reading sideband packet
fatal: 过早的文件结束符（EOF）
fatal: fetch-pack：无效的 index-pack 输出

- 二、按照教程设置，仍然出错

![1](https://github.com/leeyoshinari/OneDrive/assets/18096170/278f8b40-dada-4096-8e2c-5d1b6758ad9c)
![2](https://github.com/leeyoshinari/OneDrive/assets/18096170/c3fc8897-4be2-4224-bfa1-4cbeb20436d7)
![3](https://github.com/leeyoshinari/OneDrive/assets/18096170/b8c31f31-252e-4b6c-8f4e-0ebbe95faec8)

**Comment by leeyoshinari** [comment]
1、clone不下来的问题，你可以试试clone其他项目，大概率可能是本地配置问题。
2、nginx配置，你可以把这3个location注释掉，然后重启nginx看看页面访问正不正常，如果访问正常，就再把这3个location取消注释再重启试试

**Comment by leeyoshinari** [comment]
还有一个点特别注意：看nginx保存日志，可能没有目录读写权限；而且后端服务也要注意有没有读写权限

**Comment by bifu123** [comment]
- 一、不存在权限问题，根据config.conf中加载的文件夹配置，如下操作：

root@debian:~/OneDrive# mkdir -p /OneDrive/data /opt/data
root@debian:~/OneDrive# chmod 777 -R /OneDrive/data /opt/data
root@debian:~/OneDrive# chmod 777 ./OneDrive/* -R #给整个虚拟环境777权限

- 二、去除三个localion后的nginx.conf的server部分，这个显然对OneDrive的http://127.0.0.1:15200没有了任何代理作用

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        client_max_body_size 10240M;	# 请求体大小限制，这里是上传文件的大小
        proxy_connect_timeout 60s;	# 建立连接的超时时间
        proxy_send_timeout 600s;	# 发送请求的超时时间
        proxy_read_timeout 600s;	# 读取响应的超时时间
        location = /50x.html {
            root   html;
        }
    }
}

- 三、去除location后访问出现nginx的默认界面

![不要localsion后](https://github.com/leeyoshinari/OneDrive/assets/18096170/15b635b9-2264-477d-a8c5-dfd47f6a4e5d)


- 四、git clone https://github.com/leeyoshinari/OneDrive.git 存在问题，而其它仓库（如：git clone https://github.com/leeyoshinari/mycloud.git ）就不存在问题。

![clone出错](https://github.com/leeyoshinari/OneDrive/assets/18096170/be2dbca3-91e1-481c-946c-a9eaaa25ba9d)
![clone正确](https://github.com/leeyoshinari/OneDrive/assets/18096170/4f6bdbac-055e-49bd-b25c-cc709f9d41ed)

**Comment by bifu123** [comment]
大神，您QQ多少，便于请教！

**Comment by leeyoshinari** [comment]
已加
