### ISSUE TITLE
无法正常启动服务端

### ISSUE THREAD

**Issue by yangouyu** [leeyoshinari/OneDrive#22]
输入：sh startup.sh
显示：start server success ~

访问：127.0.0.1:15200  
回复：拒绝链接

输入：lsof -i:15200 
回复：这个端口没有开启

查看启动命令，只看到采集config.conf 的参数然后启动，执行起来没有什么问题，不能使用为啥不会报错呢。

**Comment by leeyoshinari** [comment]
执行 python3 main.py 看看报啥错
