### ISSUE TITLE
希望能增加添加FTP（主动、被动模式）功能，方便实现扩展

### ISSUE THREAD

**Issue by bifu123** [leeyoshinari/OneDrive#9]
希望能增加添加FTP（主动、被动模式）功能，方便实现扩展
我的QQ:415135222

**Comment by leeyoshinari** [comment]
你说的这个 ftp，是要往哪里传文件？

**Comment by bifu123** [comment]
一、在你写的网盘中可以添外部FTP，比如ALIST、Dzzoffice（尤其是1.0版），实现存储容量的扩展和集中管理的目的
二、提供支持onlyoffice或其它在线office在线编辑功能。
三、是否考虑手机端的界面自适应。

**Comment by leeyoshinari** [comment]
一、因为技术方案的问题，不太好加ftp这种功能，但是可以通过在服务器上挂载远程虚拟磁盘来实现你的需求。另外我还有一个项目支持分布式存储，可以看看，详见README.md
二、所有在线编辑office的功能，都需要一个高性能的服务器来部署服务，这个成本太高了，，如果用免费的服务，自己的文件将非常不安全，违背了做这个网盘的初衷了
三、手机横屏展示，页面展示还可以吧，目前我没发现页面有乱的情况。请使用比较新的手机浏览器，如果哪个页面乱了，请麻烦提供浏览器版本、手机分辨率、页面截图等信息

**Comment by bifu123** [comment]
onlyoffice我是自建的，非常安全（甚至是内网里），这个在线编辑很实用。你的程序只需要提供接口配置界面即可。
我一直用dzzoffice，它升级到2.0版后，在移动端自适应了，但是存储的文件己不是所见即所得的文件名了，就弃用了。

**Comment by leeyoshinari** [comment]
我之前也想过要支持office的在线编辑，但是没有onlyoffice🤣🤣你可以自己修改代码支持office在线编辑吧。。
